name: Release

on:
  release:
    types: [published]

jobs:
  send_chatwork:
    runs-on: ubuntu-latest
    name: Send release note to Chatwork
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Relase Notify Chatwork
        uses: ./.github/actions/release-notify-chatwork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
